artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion # folder that will be created after data_ingestion being executed 
  source_URL: F:\zizo\MLOPS\datascienceproject\data\Temp_dataset.csv
  local_data_file: artifacts/data_ingestion/Temp_dataset.csv # usually used for saving the unzip file
  
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts\data_ingestion\Temp_dataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts\data_ingestion\Temp_dataset.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts\data_transformation\train.csv
  test_data_path: artifacts\data_transformation\test.csv
  model_name: model.pt

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts\data_transformation\test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json